### ISSUE TITLE
IndexError for large factchecker queries

### ISSUE THREAD

**Issue by sbenthall** [bluestocking/bluestocking#2]
I get the following error when doing a large factchecker query.  Seems to be in the chunkerator

**Comment by sbenthall** [comment]
sb@lebenswelt:~/dev/bluestocking/bluestocking$ python factchecker.py "Jupiter is the fifth and largest planet.  Jupiter has four moons.  Jupiter is named after a Roman god."
Looking up four
Looking up named
Lookup failed
Looking up god
Looking up largest
Lookup failed
Looking up planet
Looking up Roman
Looking up Jupiter
Looking up moons
Traceback (most recent call last):
  File "factchecker.py", line 57, in <module>
    main()
  File "factchecker.py", line 44, in main
    doxes = [lookup_word(w) for w in words]
  File "factchecker.py", line 27, in lookup_word
    dox = parse.Document(content).to_dox()
  File "/home/sb/dev/bluestocking/bluestocking/parse.py", line 26, in to_dox
    return doxament.Doxament(Parser(self).parse_relations())
  File "/home/sb/dev/bluestocking/bluestocking/parse.py", line 52, in parse_relations
    sentences,chunker = self.preprocess(sentences)
  File "/home/sb/dev/bluestocking/bluestocking/parse.py", line 73, in preprocess
    sent = c.chunk_sent(sentence)
  File "/home/sb/dev/bluestocking/bluestocking/chunkerator.py", line 82, in chunk_sent
    tree = self.neg(tree)
  File "/home/sb/dev/bluestocking/bluestocking/chunkerator.py", line 47, in neg
    if tree[jj][1][1]!="C":
IndexError: string index out of range
